######################################################################
# Automatically generated by qmake (2.01a) Mo. Jan 21 22:51:22 2013
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testqstring.cpp
